title: Your awesome title
author: Milabknowin
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I have to learn to be more comfortable talking about myself. I am worthy of conversation. I'm smart, funny and beautiful!

# social links
instagram_username: milabknowin
github_username:  milabknowin

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
